name: Github Pages CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i yarn -g
      - run: yarn
      - run: yarn run build
      - name: Deploy
        run: |
          git config --global user.name "jottenlips"
          git config --global user.email "jottenlips@gmail.com"
          yarn run gh-pages -d build --repo https://jottenlips:$GITHUB_TOKEN@github.com/jottenlips/making-midi.git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CI: true
